services:
    db:
        image: mysql:8
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - db:/var/lib/mysql
        env_file:
            - .env
volumes:
    db:
